import 'package:fluxa_app/core/icons/app_huge_icons.dart';

class CategoryIconMapper {
  CategoryIconMapper._();

  static AppIconData fromKey(String? key) {
    switch (key) {
      case 'food':
      case 'breakfast':
      case 'lunch':
      case 'dinner':
      case 'restaurant':
        return AppHugeIcons.restaurant_outlined;
      case 'coffee':
        return AppHugeIcons.local_cafe_outlined;
      case 'snack':
        return AppHugeIcons.fastfood_outlined;
      case 'groceries':
        return AppHugeIcons.local_grocery_store_outlined;
      case 'transport':
      case 'bus':
        return AppHugeIcons.directions_bus_outlined;
      case 'train':
        return AppHugeIcons.train_outlined;
      case 'taxi':
        return AppHugeIcons.local_taxi_outlined;
      case 'fuel':
        return AppHugeIcons.local_gas_station_outlined;
      case 'parking':
        return AppHugeIcons.local_parking_outlined;
      case 'online_ride':
        return AppHugeIcons.two_wheeler_outlined;
      case 'vehicle_service':
        return AppHugeIcons.car_repair_outlined;
      case 'shopping':
        return AppHugeIcons.shopping_bag_outlined;
      case 'clothes':
        return AppHugeIcons.checkroom_outlined;
      case 'shoes':
        return AppHugeIcons.shopping_bag_outlined;
      case 'accessories':
        return AppHugeIcons.watch_outlined;
      case 'electronics':
        return AppHugeIcons.devices_outlined;
      case 'marketplace':
        return AppHugeIcons.storefront_outlined;
      case 'personal_care':
        return AppHugeIcons.spa_outlined;
      case 'housing':
        return AppHugeIcons.home_outlined;
      case 'rent':
        return AppHugeIcons.key_outlined;
      case 'electricity':
        return AppHugeIcons.bolt_outlined;
      case 'water':
        return AppHugeIcons.water_drop_outlined;
      case 'internet':
        return AppHugeIcons.wifi_outlined;
      case 'furniture':
        return AppHugeIcons.chair_outlined;
      case 'cleaning':
        return AppHugeIcons.cleaning_services_outlined;
      case 'home_repair':
        return AppHugeIcons.handyman_outlined;
      case 'entertainment':
      case 'movie':
        return AppHugeIcons.movie_outlined;
      case 'music':
        return AppHugeIcons.music_note_outlined;
      case 'game':
        return AppHugeIcons.sports_esports_outlined;
      case 'concert':
        return AppHugeIcons.music_note_outlined;
      case 'streaming':
        return AppHugeIcons.play_circle_outline;
      case 'vacation':
        return AppHugeIcons.flight_takeoff_outlined;
      case 'hobby':
        return AppHugeIcons.palette_outlined;
      case 'health':
        return AppHugeIcons.medical_services_outlined;
      case 'doctor':
        return AppHugeIcons.medical_services_outlined;
      case 'medicine':
        return AppHugeIcons.medication_outlined;
      case 'hospital':
        return AppHugeIcons.local_hospital_outlined;
      case 'insurance':
        return AppHugeIcons.health_and_safety_outlined;
      case 'gym':
        return AppHugeIcons.fitness_center_outlined;
      case 'vitamin':
        return AppHugeIcons.local_pharmacy_outlined;
      case 'education':
        return AppHugeIcons.school_outlined;
      case 'course':
        return AppHugeIcons.menu_book_outlined;
      case 'book':
        return AppHugeIcons.book_outlined;
      case 'tuition':
        return AppHugeIcons.account_balance_outlined;
      case 'seminar':
        return AppHugeIcons.groups_outlined;
      case 'certification':
        return AppHugeIcons.workspace_premium_outlined;
      case 'stationery':
        return AppHugeIcons.edit_outlined;
      case 'bill':
        return AppHugeIcons.receipt_long_outlined;
      case 'phone_credit':
        return AppHugeIcons.phone_android_outlined;
      case 'mobile_data':
        return AppHugeIcons.signal_cellular_alt_outlined;
      case 'subscription':
        return AppHugeIcons.subscriptions_outlined;
      case 'credit_card':
        return AppHugeIcons.credit_card_outlined;
      case 'loan':
        return AppHugeIcons.payments_outlined;
      case 'tax':
        return AppHugeIcons.request_quote_outlined;
      case 'salary':
      case 'monthly_salary':
      case 'salary_bonus':
        return AppHugeIcons.payments_outlined;
      case 'allowance':
      case 'overtime':
        return AppHugeIcons.account_balance_wallet_outlined;
      case 'freelance':
      case 'project':
        return AppHugeIcons.work_outline;
      case 'design':
        return AppHugeIcons.design_services_outlined;
      case 'development':
        return AppHugeIcons.code_outlined;
      case 'writing':
        return AppHugeIcons.article_outlined;
      case 'consultation':
        return AppHugeIcons.support_agent_outlined;
      case 'business':
      case 'product_sales':
      case 'service_sales':
        return AppHugeIcons.storefront_outlined;
      case 'profit':
      case 'commission':
        return AppHugeIcons.trending_up_outlined;
      case 'investment':
      case 'capital_gain':
      case 'stock':
        return AppHugeIcons.trending_up_outlined;
      case 'dividend':
      case 'interest':
        return AppHugeIcons.savings_outlined;
      case 'crypto':
        return AppHugeIcons.attach_money;
      case 'gift':
      case 'gift_out':
      case 'prize':
        return AppHugeIcons.card_giftcard_outlined;
      case 'family':
        return AppHugeIcons.group_outlined;
      case 'friend':
        return AppHugeIcons.people_outline;
      case 'reward':
        return AppHugeIcons.emoji_events_outlined;
      case 'refund':
      case 'cashback':
      case 'reimbursement':
        return AppHugeIcons.replay_outlined;
      case 'debt_paid':
        return AppHugeIcons.handshake_outlined;
      case 'donation':
        return AppHugeIcons.volunteer_activism_outlined;
      case 'admin_fee':
        return AppHugeIcons.admin_panel_settings_outlined;
      case 'unexpected':
        return AppHugeIcons.error_outline;
      case 'other':
      case 'other_expense':
      case 'other_income':
      default:
        return AppHugeIcons.category_outlined;
    }
  }
}




