import 'package:flutter/material.dart';

class CategoryIconMapper {
  CategoryIconMapper._();

  static IconData fromKey(String? key) {
    switch (key) {
      case 'food':
      case 'breakfast':
      case 'lunch':
      case 'dinner':
      case 'restaurant':
        return Icons.restaurant_outlined;
      case 'coffee':
        return Icons.local_cafe_outlined;
      case 'snack':
        return Icons.fastfood_outlined;
      case 'groceries':
        return Icons.local_grocery_store_outlined;
      case 'transport':
      case 'bus':
        return Icons.directions_bus_outlined;
      case 'train':
        return Icons.train_outlined;
      case 'taxi':
        return Icons.local_taxi_outlined;
      case 'fuel':
        return Icons.local_gas_station_outlined;
      case 'parking':
        return Icons.local_parking_outlined;
      case 'online_ride':
        return Icons.two_wheeler_outlined;
      case 'vehicle_service':
        return Icons.car_repair_outlined;
      case 'shopping':
        return Icons.shopping_bag_outlined;
      case 'clothes':
        return Icons.checkroom_outlined;
      case 'shoes':
        return Icons.shopping_bag_outlined;
      case 'accessories':
        return Icons.watch_outlined;
      case 'electronics':
        return Icons.devices_outlined;
      case 'marketplace':
        return Icons.storefront_outlined;
      case 'personal_care':
        return Icons.spa_outlined;
      case 'housing':
        return Icons.home_outlined;
      case 'rent':
        return Icons.key_outlined;
      case 'electricity':
        return Icons.bolt_outlined;
      case 'water':
        return Icons.water_drop_outlined;
      case 'internet':
        return Icons.wifi_outlined;
      case 'furniture':
        return Icons.chair_outlined;
      case 'cleaning':
        return Icons.cleaning_services_outlined;
      case 'home_repair':
        return Icons.handyman_outlined;
      case 'entertainment':
      case 'movie':
        return Icons.movie_outlined;
      case 'music':
        return Icons.music_note_outlined;
      case 'game':
        return Icons.sports_esports_outlined;
      case 'concert':
        return Icons.music_note_outlined;
      case 'streaming':
        return Icons.play_circle_outline;
      case 'vacation':
        return Icons.flight_takeoff_outlined;
      case 'hobby':
        return Icons.palette_outlined;
      case 'health':
        return Icons.medical_services_outlined;
      case 'doctor':
        return Icons.medical_services_outlined;
      case 'medicine':
        return Icons.medication_outlined;
      case 'hospital':
        return Icons.local_hospital_outlined;
      case 'insurance':
        return Icons.health_and_safety_outlined;
      case 'gym':
        return Icons.fitness_center_outlined;
      case 'vitamin':
        return Icons.local_pharmacy_outlined;
      case 'education':
        return Icons.school_outlined;
      case 'course':
        return Icons.menu_book_outlined;
      case 'book':
        return Icons.book_outlined;
      case 'tuition':
        return Icons.account_balance_outlined;
      case 'seminar':
        return Icons.groups_outlined;
      case 'certification':
        return Icons.workspace_premium_outlined;
      case 'stationery':
        return Icons.edit_outlined;
      case 'bill':
        return Icons.receipt_long_outlined;
      case 'phone_credit':
        return Icons.phone_android_outlined;
      case 'mobile_data':
        return Icons.signal_cellular_alt_outlined;
      case 'subscription':
        return Icons.subscriptions_outlined;
      case 'credit_card':
        return Icons.credit_card_outlined;
      case 'loan':
        return Icons.payments_outlined;
      case 'tax':
        return Icons.request_quote_outlined;
      case 'salary':
      case 'monthly_salary':
      case 'salary_bonus':
        return Icons.payments_outlined;
      case 'allowance':
      case 'overtime':
        return Icons.account_balance_wallet_outlined;
      case 'freelance':
      case 'project':
        return Icons.work_outline;
      case 'design':
        return Icons.design_services_outlined;
      case 'development':
        return Icons.code_outlined;
      case 'writing':
        return Icons.article_outlined;
      case 'consultation':
        return Icons.support_agent_outlined;
      case 'business':
      case 'product_sales':
      case 'service_sales':
        return Icons.storefront_outlined;
      case 'profit':
      case 'commission':
        return Icons.trending_up_outlined;
      case 'investment':
      case 'capital_gain':
      case 'stock':
        return Icons.trending_up_outlined;
      case 'dividend':
      case 'interest':
        return Icons.savings_outlined;
      case 'crypto':
        return Icons.attach_money;
      case 'gift':
      case 'gift_out':
      case 'prize':
        return Icons.card_giftcard_outlined;
      case 'family':
        return Icons.group_outlined;
      case 'friend':
        return Icons.people_outline;
      case 'reward':
        return Icons.emoji_events_outlined;
      case 'refund':
      case 'cashback':
      case 'reimbursement':
        return Icons.replay_outlined;
      case 'debt_paid':
        return Icons.handshake_outlined;
      case 'donation':
        return Icons.volunteer_activism_outlined;
      case 'admin_fee':
        return Icons.admin_panel_settings_outlined;
      case 'unexpected':
        return Icons.error_outline;
      case 'other':
      case 'other_expense':
      case 'other_income':
      default:
        return Icons.category_outlined;
    }
  }
}
